### PR TITLE
Added an option to save the test report to a file

### PR DESCRIPTION
**Pull request by koleror**

### CODE REVIEW

**Comment by mjhea0** [comment]
@koleror it looks like each of the Travis tests are failing with:

The command "flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark django_slowtests" exited with 1.

Can you take a look at this?

**Comment by koleror** [comment]
I know but did not really want to modify the run function too much, as it's been copied/past from unittest, with only one additional line (the last one before the return), so I wanted to make the change readable :) 
But I can split it if you prefer.

**Comment by mjhea0** [comment]
Just update this line, changing the `max-line-length` and `max-complexity` to get it to pass for now.

```
flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark django_slowtests
```

**Comment by koleror** [comment]
Ok, thanks! 
I'll do it now

**Pull request merged**
